install:
	sudo apt-get --yes --force-yes install python
	sudo apt-get --yes --force-yes install imagemagick
	pip install simplejson
	chmod +x pktex-resize.py
	sudo cp pktex-resize.py /usr/bin/pktex-resize
